### ISSUE TITLE
Transparent markers

### ISSUE THREAD

**Issue by ma-laforge** [tbreloff/Plots.jl#151]
Hi Tom,

I cannot currently find a way to render markers with transparent fill.  I tried setting markeralpha=0 & fillalpha=0, but neither works.  markeralpha=0 makes the markerstroke transparent as well.

Currently, my workaround is to assign markercolor=[background color], but it is not the same (hides the plot line).

Is this supported/could it be supported in the future?

**Comment by tbreloff** [comment]
This should work... Which backend are you using?

**Comment by tbreloff** [comment]
This mostly works... but I think there's a bug in matplotlib (it works for scatter, but not plot).  I made a couple fixes to the dev branch, so try:

```julia
Pkg.checkout("Plots","dev")
using Plots; gadfly()
plot(rand(10), marker = (20,0.3,stroke(5,:green,1.0)))
```

It should give you semitransparent markers with solid green strokes.

**Comment by ma-laforge** [comment]
You are correct: It does indeed work with Gadfly.

I noticed the problem in PyPlot.  For PyPlot, I find I need to set the "`fillstyle`" kwarg:

`fillstyle="none"` instead of `fillstyle="full"`

...I don't know if there is a generic alpha setting, though.

**Comment by tbreloff** [comment]
I just went to confirm the behavior on my desktop machine, and pyplot works as expected!  I'm running matplotlib version 1.5 there.  On my OSX laptop with matplotlib version 1.4.3, the stroke inherits the alpha from the fill.  So it's seemingly a matplotlib bug which was fixed.

**Comment by ma-laforge** [comment]
Oh, sorry about that.  I forgot I *am* using an old version of matplotlib.

I had to use an older version to get some other software working simultaneously.  I'm still having issues getting multiple Python packages to play nice together.

**Comment by mdg411** [comment]
Hi! For me, the simple example above works with PyPlot but not with GR. The marker stroke still inherits the alpha from the fill. I know it's an old issue, but I didn't find anything else on this. Could anyone point me to a solution or is this still a bug? Thanks!

```julia
using Plots; gr()
plot(rand(10), marker = (20,0.3,stroke(5,:green,1.0)))
```
![image](https://user-images.githubusercontent.com/11853178/176222714-3f5d28c7-d956-4713-b847-76b0632d85d1.png)
```julia
using Plots; pyplot()
plot(rand(10), marker = (20,0.3,stroke(5,:green,1.0)))
```
![image](https://user-images.githubusercontent.com/11853178/176222529-a2994f96-99e5-401d-a40c-044fb2501373.png)


Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, tigerlake)
