### ISSUE TITLE
GR meta issue

### ISSUE THREAD

**Issue by tbreloff** [tbreloff/Plots.jl#314]
Lets try to consolidate GR-specific bugs and missing features here:

**Comment by tbreloff** [comment]
Notes on transparency:

> Transparency should work for SVG, PDF, OS X and Windows.
For PNG output, the GR driver (GKS) has to be changed to Cairo (Unix + OS X)

I forgot about this.  Transparency status (only tested on Ubuntu Linux):

- GUI: no
- PNG: no
- SVG: yes

**Comment by tbreloff** [comment]
Just tested on OS X... transparency works with the gui.

**Comment by tbreloff** [comment]
Note: I get the same error as in #271 writing PNG on OS X:

```

julia> using Plots; gr(); scatter(1:1000,zcolor=1:1000, c=:blues)
[Plots.jl] Initializing backend: gr

julia> png("/tmp/tmp")
GKS: Ghostscript support not compiled in
ERROR: SystemError: opening file gks.png: No such file or directory
 in open at ./iostream.jl:90
 in open at ./iostream.jl:112
 in _writemime at /Users/tom/.julia/v0.4/Plots/src/backends/gr.jl:1084
 in writemime at /Users/tom/.julia/v0.4/Plots/src/output.jl:150
 in png at /Users/tom/.julia/v0.4/Plots/src/output.jl:8
 in png at /Users/tom/.julia/v0.4/Plots/src/output.jl:11
```

**Comment by tbreloff** [comment]
@jheinen Any idea how to have a border around scatter markers (the "marker stroke")?  I've tried a few different things setting lines, etc, and nothing seems to draw the border.  Is it possible?

**Comment by tbreloff** [comment]
It seems like GR doesn't handle non-positive data on a log scale very well.  See https://github.com/tbreloff/Plots.jl/issues/326#issuecomment-225440072 for how I think it should look.  This is what it looks like:

![tmp](https://cloud.githubusercontent.com/assets/933338/15991954/03b1819a-308f-11e6-815d-78e25a8f5393.png)

This:

```
x=linspace(0,20,100); plot(x,abs(5sin(x)),xscale=:log,yscale=:log)
```

will produce:

![tmp](https://cloud.githubusercontent.com/assets/933338/15991969/4a19942e-308f-11e6-8f8c-c912ee675c83.png)

and this:

```
x=linspace(1e-1,20,100); plot(x,abs(5sin(x)),xscale=:log,yscale=:log)
```

will produce:

![tmp](https://cloud.githubusercontent.com/assets/933338/15991982/66cb4e3c-308f-11e6-8913-a4e64167329c.png)

@jheinen Is this a limitation of GR, or the way that we're doing it in Plots?

**Comment by jheinen** [comment]
Yes. Right now, the minimum limit of any axes set to log scale must be > 0.

**Comment by tbreloff** [comment]
Ok thanks @jheinen.  I'll make a note of that.

**Comment by jheinen** [comment]
I can probably add this feature later, but the transformation would no longer be affine ...

**Comment by tbreloff** [comment]
Josef I think there are other things that are higher priority... This
sounds like a big change. But if you do decide to tackle it, I think
matching pyplot's symlog transformation is probably best.

**Comment by tbreloff** [comment]
@jheinen Looking through the list, the most important thing for me is the marker stroke.  Right now there is no stroke, and I'd really like that to be fully supported.  Any thoughts on how we could get that working?  Just compare:

```
pyplot(); scatter(randn(100),randn(100),m=(15,0.5,stroke(3,0.9)))
```

![tmp](https://cloud.githubusercontent.com/assets/933338/16133043/e05bd882-33e3-11e6-9323-eea198af08fd.png)


```
gr(); scatter(randn(100),randn(100),m=(15,0.5,stroke(3,0.9)))
```

![tmp](https://cloud.githubusercontent.com/assets/933338/16133061/f9d844d0-33e3-11e6-9136-094adbbadc60.png)

**Comment by diegozea** [comment]
I guess this issue is part of "handle discrete axes":  

![image](https://cloud.githubusercontent.com/assets/2822757/16715780/14262f5c-46c0-11e6-98ff-bc9c7f8e0866.png)

**Comment by tbreloff** [comment]
Several of the unfinished items above could be solved if I just draw the axes and gridlines myself.  I have this capability with PlotUtils and the layout framework of Plots, I just have to do it.

**Comment by jgbos** [comment]
I see you checked off the issue regarding #271, but I'm having the same issue using `@manipulate` running on CentOS Linux.  Is there a commit that fixes this?

**Comment by tbreloff** [comment]
I was having the error, and then I wasn't. I don't remember exactly what I
fixed though. Can you give me more detail on your setup? Pkg.status?

**Comment by jgbos** [comment]
Below is Pkg.status, but the gist is:  

- CentOS 6.6
- Julia 0.4.5 release
- latest `dev` branch
- using `gr` backend (latest version after a Pkg.update())

```
23 required packages:
 - CUBLAS                        0.0.2
 - CUDNN                         0.3.0
 - DSP                           0.0.11
 - Distributions                 0.9.0
 - ForwardDiff                   0.2.1
 - GR                            0.13.0
 - IJulia                        1.1.10
 - ImageMagick                   0.1.6
 - Images                        0.5.5
 - Interact                      0.3.1
 - Lint                          0.2.4
 - MATLAB                        0.2.4
 - MNIST                         0.0.2
 - Memoize                       0.0.1
 - PGFPlots                      1.3.5
 - PlotUtils                     0.0.3
 - PlotlyJS                      0.3.1
 - Plots                         0.8.0+             dev (dirty)
 - ProgressMeter                 0.3.2
 - ProtoBuf                      0.1.6
 - PyCall                        1.6.3
 - PyPlot                        2.2.0
 - Quaternions                   0.1.1
69 additional packages:
 - ArgParse                      0.3.0
 - BinDeps                       0.3.21
 - Blink                         0.3.4
 - Blosc                         0.1.5
 - CUDAdrv                       0.1.0+             master
 - CUDArt                        0.2.3
 - Calculus                      0.1.15
 - Codecs                        0.1.5
 - ColorBrewer                   0.3.0
 - ColorTypes                    0.2.3
 - ColorVectorSpace              0.1.4
 - Colors                        0.6.5
 - Compat                        0.8.4
 - Conda                         0.2.2
 - Contour                       0.1.0
 - DataStructures                0.4.4
 - Dates                         0.4.4
 - DualNumbers                   0.2.2
 - FileIO                        0.1.0
 - FixedPointNumbers             0.1.3
 - FixedSizeArrays               0.2.2
 - Graphics                      0.1.3
 - HDF5                          0.6.3
 - Hiccup                        0.0.2
 - HttpCommon                    0.2.6
 - HttpParser                    0.1.1
 - HttpServer                    0.1.5
 - JLD                           0.6.3
 - JSON                          0.6.0
 - JavaCall                      0.3.4+             master
 - LaTeXStrings                  0.1.6
 - Lazy                          0.10.1
 - LegacyStrings                 0.1.1
 - MacroTools                    0.3.0
 - MbedTLS                       0.2.5
 - Measures                      0.0.2
 - Mustache                      0.0.15
 - Mux                           0.2.0
 - NaNMath                       0.2.1
 - Nettle                        0.2.3
 - OpenAIGym                     0.0.0-             master (unregistered)
 - P                             0.0.0-             non-repo (unregistered)
 - PDMats                        0.4.2
 - Polynomials                   0.0.5
 - Reactive                      0.3.3
 - RecipesBase                   0.0.6
 - Reexport                      0.0.3
 - Requires                      0.2.2
 - Rmath                         0.1.0
 - SHA                           0.1.2
 - SIUnits                       0.0.6
 - StatsBase                     0.8.3
 - StatsFuns                     0.3.0
 - TexExtensions                 0.0.3
 - TextWrap                      0.1.5
 - TikzPictures                  0.3.2
 - URIParser                     0.1.5
 - WebSockets                    0.1.2
 - ZMQ                           0.3.2
 - Zlib                          0.1.12
```

**Comment by jgbos** [comment]
actually, I guess the error is slightly different then #271 

```
GKS: libgs.so.9: cannot open shared object file: No such file or directory

SystemError: opening file /tmp/juliaRc47QV.png: No such file or directory

 in open at ./iostream.jl:90
 in open at ./iostream.jl:112
 in readall at io.jl:266
 in _writemime at /home/user/.julia/v0.4/Plots/src/backends/gr.jl:972
 in writemime at /home/user/.julia/v0.4/Interact/src/IJulia/setup.jl:103
 in base64encode at base64.jl:160
 in display_dict at /home/user/.julia/v0.4/IJulia/src/execute_request.jl:32

```

**Comment by tbreloff** [comment]
@jheinen Any idea?

Also... cool to see you have OpenAIGym 👍 What are you working on?

**Comment by jgbos** [comment]
Mostly playing with OpenAIGym to learn, but working on proposals at my job related to reinforcement learning and deep learning.  Fun stuff.

**Comment by jheinen** [comment]
There is a problem with the "generic linux' binary runtime, e.g. ``gsplugin.so`` has dependencies to system libraries, which should not happen. We will fix this next week and tag a new version. I probably will also make the Cairo driver the default choice for creating PNGs.

**Comment by jgbos** [comment]
Thanks! btw, I first encountered this by trying to get the `gr(display_type=:inline)` to work in tmux.  I had switched PDF to PNG and got this same error.

**Comment by jheinen** [comment]
Our build system must have been changed and it turns out that I have to make further tests and checks with the resulting shared libraries to avoid such problems. If everything works fine, the run-time (used for the Julia build) should be self-contained.

**Comment by jheinen** [comment]
Could you please try to rebuild/reinstall GR. I patched the Linux run-time to use the Cairo graphics driver to render PNGs. If it works, I'll make that the default (for all platforms) and tag a new version next week ...

**Comment by jgbos** [comment]
@jheinen apologies, for some reason I only just saw you responded last night with a fix.  Very strange.  I was able to run with the GR backend in the notebook with `@manipulate`

**Comment by baggepinnen** [comment]
Attribute `ribbon` does not work as intended with backend `gr`
```julia
gr()
plot(randn(10), ribbon = [2,1])
plot(randn(10), ribbon = (ones(10),2ones(10)))
```

**Comment by jheinen** [comment]
@tbreloff , ``frng`` seems to be a tuple - using ``frng[1]`` works. Does this make sense? 

```
                # do area fill
                if frng != nothing
                    gr_set_fillcolor(d[:fillcolor], d[:fillalpha])
                    GR.setfillintstyle(GR.INTSTYLE_SOLID)
                    frng = isa(frng, Number) ? Float64[frng] : frng[1]
                    nx, ny, nf = length(x), length(y), length(frng)
                    n = max(nx, ny)
                    fx, fy = zeros(2n), zeros(2n)
                    for i=1:n
                        fx[i] = fx[end-i+1] = cycle(x,i)
                        fy[i] = cycle(y,i)
                        fy[end-i+1] = cycle(frng,i)
                    end
                    GR.fillarea(fx, fy)
                end
```

**Comment by tbreloff** [comment]
no that's not right, but I'll make the fix right now

**Comment by tbreloff** [comment]
Fixed and improved.  I also added support for fill areas split by NaNs, each with their own color:

```julia
using Plots; gr()
plot([1,2,NaN,3,4,NaN,5,6],randn(8), fill=(0, [:red,:green,:purple]), line=5)
```

![tmp](https://cloud.githubusercontent.com/assets/933338/17114347/7effe97c-527c-11e6-8587-d3b10db57541.png)

julia 0.5 only - dev branch

**Comment by baggepinnen** [comment]
I'm not sure if the above comments were targeted at improving the `fillrange` problems, but I still have issues with `ribbon` on GR, Julia 0.5 Plots-dev

**Comment by tbreloff** [comment]
A note on how to implement clim:

- need to update the `normalize_zvals` method to check for clims when setting vmin/vmax
- need to specify range in call to `GR.colorbar()` in `gr_colorbar(sp)`.  Looking at the GR code, it seems like I should do something like this before I call it: `GR.jlgr.plt.kvs[:zrange] = cmin, cmax`

@jheinen will overriding `:zrange` like that mess up anything else?  Should we update the `GR.colorbar` method to use another source for this data?

cc: @ahwillia

**Comment by jheinen** [comment]
@tbreloff
 I think - for Plots.jl - we have to change the scaling of the Z axis (using ``GR.setspace(zmin, zmax, ...)``) using ``cmin`` and ``cmax``.

**Comment by daschw** [comment]
Hi @tbreloff, I already reported this earlier this week on gitter. For me the Cropping issue (https://github.com/tbreloff/Plots.jl/issues/405) is not fixed (or I'm having another issue).
```
using Plots; gr()
plot(rand(10), xlabel="my x label", ylabel="my y label")
savefig("testfig.png")
```
results in a cropped xlabel and a missing ylabel
![testfig](https://cloud.githubusercontent.com/assets/16589944/20581333/7d433ce0-b1d8-11e6-8068-fd0aae61373b.png)
I'm on Julia Version 0.5.0 and I already tried `Pkg.update()`, `Pkg.build()`, `Pkg.checkout("Plots")` and `Pkg.checkout("GR")` on a Windows 7 and an Archlinux machine, but the issue persists in all scenarios. Any idea what could be wrong with my configuration(s)?

**Comment by tbreloff** [comment]
I suspect you still have an old GR installed. Maybe @jheinen can help?

**Comment by daschw** [comment]
OK, so neither `Pkg.update()` nor `Pkg.build()` helped, but `Pkg.rm("GR")` and `Pkg.add("GR")` resolved the issue for me.

**Comment by jheinen** [comment]
I have to improve the build process. To force an update of the GR run-time, you can temporary set the GRDIR environment to an empty string:

ENV["GRDIR"]=""
Pkg.build("GR")

This should always work.

But I'll implement an easier solution with the next release ....

**Comment by mkborregaard** [comment]
When rotating x axis labels in gr, they are rotated around their center and thus overlaps with the plot region. Increasing bottom_margen does not help.
![skaermbillede 2017-02-08 kl 11 55 39](https://cloud.githubusercontent.com/assets/8429802/22734333/9b5644bc-edf5-11e6-8af5-c397724583f8.png)
it works in pyplot()
![skaermbillede 2017-02-08 kl 11 55 50](https://cloud.githubusercontent.com/assets/8429802/22734343/a4570902-edf5-11e6-846e-0f575f23c13d.png)

**Comment by jheinen** [comment]
I will first implement this in GR - currently, GR overwrites the character up vector when drawing axes - and then use similar code in Plots.jl.

**Comment by mkborregaard** [comment]
cf https://github.com/JuliaPlots/Plots.jl/issues/757

**Comment by mkborregaard** [comment]
GR places tickmarks wrong in heatmap, and heatmap ignores `ticks`.
<img width="345" alt="skaermbillede 2017-04-12 kl 12 02 29" src="https://cloud.githubusercontent.com/assets/8429802/24952501/f4b688b0-1f77-11e7-8613-104c61ed20c6.png">
<img width="593" alt="skaermbillede 2017-04-12 kl 12 02 37" src="https://cloud.githubusercontent.com/assets/8429802/24952512/fa984020-1f77-11e7-9f1d-0998432a443e.png">
1, 2 and 3 should correspond to the middle of each box.

**Comment by jheinen** [comment]
I just fixed this in https://github.com/jheinen/GR.jl/commit/f37b71d2603dd0e51c6bf43e12bfeecae8d80805 - will apply the change to the `Plots` `gr()` backend ASAP

**Comment by jheinen** [comment]
The axes limits are expanded now, but tick marks are still hidden because `Plots` uses its "own" axes routines => WIP
